# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from asgiref.sync import sync_to_async
from datetime import datetime
from django.db import models, transaction
from django.db.models import F
from typing import Any
from zghmvp.apps.base import models
from zghmvp.apps.report.tools.log import PrintLineStatus
from zghmvp.tools.models import get_fields, get_float_fields, get_int_fields, get_time_fields
import contextlib
import functools
import numpy
import os
import pandas

def parse_int(s: str, default: Any) -> int:
    ...

def parse_float(s: str, default: Any, is_percentage: bool) -> float:
    ...

def fromtimestamp(t: int, format_: str | None) -> datetime | str | None:
    ...

def async_transaction(func: Any) -> Any:
    ...

def format_site_info(df: pandas.DataFrame) -> pandas.DataFrame:
    ...

def format_cityareal_info(df: pandas.DataFrame, city_id: bool, areal_id: bool, city_name: bool, areal_name: bool, partner_name: bool, inplace: bool) -> pandas.DataFrame:
    ...

def format_field_data(base_model: Any, df: pandas.DataFrame, rename: dict | None, exclude: tuple) -> Any:
    ...

def format_and_create(base_model: models.Model, df: pandas.DataFrame, rename: dict | None, exclude: tuple, delete_old_filter: dict | None, print_status: bool) -> pandas.DataFrame:
    ...

def format_and_create_or_update(base_model: models.Model, unique_fields: list[str], df: pandas.DataFrame, rename: dict | None, exclude: tuple, print_status: bool) -> Any:
    ...

def get_site_error_name(site_list: list[int] | pandas.Series | pandas.DataFrame, groupby_areal: bool, groupby_city: bool) -> list[str]:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import contextlib
import functools
import os
import datetime
import numpy
import pandas
import asgiref
import asgiref.sync
import django
import django.db
import django.db.models
import django.db.transaction
import django.db.models.F
import zghmvp
import zghmvp.apps
import zghmvp.apps.base
import zghmvp.apps.base.models
import zghmvp.apps.report
import zghmvp.apps.report.tools
import zghmvp.apps.report.tools.log
import zghmvp.tools
import zghmvp.tools.models