# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from collections import UserDict
from collections.abc import Callable, Generator
from datetime import datetime
from io import BytesIO
from openpyxl.worksheet.worksheet import Worksheet
from pathlib import Path
from tempfile import TemporaryDirectory, mkstemp
from typing import Any, IO, TYPE_CHECKING
from typing_extensions import Self
from zghmvp.apps.report.tools.path import get_date_data_dir, get_today_data_dir
from zghmvp.tools.zipfile import ZipFile
import numpy
import os
import pandas
import polars
import re
import xlwings

def polars_read_excel(source: str | Path | IO[bytes] | bytes) -> pandas.DataFrame:
    ...

def polars_read_csv(source: str | Path | IO[str] | IO[bytes] | bytes) -> Any:
    ...

class DictDataFrame(UserDict):
    def __init__(self: Self) -> None: ...
    def pop(self: Self, key: str | int | tuple) -> Any: ...
    def copy(self: Self) -> Any: ...
    def items(self: Self) -> Any: ...
    def __getitem__(self: Self, key: str | int | tuple) -> Any: ...
    def __setitem__(self: Self, key: str | int | tuple, value: str | dict) -> None: ...

def get_all_file_path(directory: str, filter_file_name: str, suffix: str | tuple[str, ...]) -> Generator[str, None, None]:
    ...

def get_all_file_to_dataframe(directory: str, sheet_name: int | str | list[int] | dict[str, int | str], filter_file_name: str, log: Callable | None) -> Generator[pandas.DataFrame, None, None]:
    ...

def get_all_file_to_dict_dataframe(directory: str, rename: Callable | str | None) -> dict[str, pandas.DataFrame]:
    ...

class UnzipExcelFilesManager:
    def __init__(self: Self, path: Any, rename_sheet: Any) -> None: ...
    def rename_columns(self: Self, all_columns: dict[str, str] | None, sheet_columns: dict[str, str] | None, sheet_callback: dict[str, Callable[[pandas.DataFrame], str]] | None) -> None: ...
    def save_to(self: Self, save_to: str | Path | BytesIO) -> None: ...
    def __enter__(self: Self) -> Any: ...
    def __exit__(self: Self, exc_type: Any, exc_val: Any, exc_tb: Any) -> Any: ...

class ExcelWriterManager:
    def __init__(self: Self, data_date: datetime | None, sub_dir: str | None, file_name: str | None, path: str | None, print_msg: str | None, print_status: bool, use_xlwings_save: bool) -> None: ...
    def __enter__(self: Self) -> 'ExcelWriterManager': ...
    def to_excel(self: Self, df: pandas.DataFrame | polars.DataFrame, index: Any, sheet_name: str, delete_index: bool) -> None: ...
    def __exit__(self: Self, exc_type: Any, exc_val: Any, exc_tb: Any) -> Any: ...

def apply_field_types(df: pandas.DataFrame, field_types: dict[str, str], fill_value: dict | None) -> None:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import re
import collections
import collections.UserDict
import collections.abc
import datetime
import io
import pathlib
import tempfile
import typing
import numpy
import pandas
import polars
import xlwings
import zghmvp
import zghmvp.apps
import zghmvp.apps.report
import zghmvp.apps.report.tools
import zghmvp.apps.report.tools.path
import zghmvp.tools
import zghmvp.tools.zipfile
import ntpath