# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from datetime import date, timedelta
from io import BytesIO
from typing import Any, TYPE_CHECKING, cast
from typing_extensions import Self
from zghmvp.apps.report import models
from zghmvp.apps.report.tools.dengta import 灯塔
from zghmvp.apps.report.tools.format import format_and_create, format_site_info
from zghmvp.config import COMPANY
from zghmvp.tools.format import auto_datetime_convert
from zghmvp.tools.pl import PlTools, TRenameConfigType, UnzipExcelFilesManager
import polars
import re

RENAME_ALL_DF_COLUMNS: dict[str, str] = {'城市名': '城市', 'city_name': '城市', '站点名': '站点名称', '站点': '站点名称', '门店名称': '站点名称', 'poi_name': '站点名称', '站点id': '站点ID', 'poi_id': '站点ID', '门店id': '门店ID', 'dt': '日期', '骑手名称': '骑手姓名', '骑手名': '骑手姓名', '配送员': '骑手姓名', '配送员ID': '骑手ID', 'rider_name': '骑手姓名', 'rider_id': '骑手ID', 'dispatcher_mis': '骑手mis号', '骑手mis': '骑手mis号', '订单id': '订单ID', 'order_id': '订单ID'}
RENAME_DF_COLUMNS: dict[str, TRenameConfigType | None] = {'核心数据': dict(RENAME_ALL_DF_COLUMNS, **{'配送原因未完成订单占比（未完成全部当作取消）': '配送原因未完成订单占比_未完成全部当作取消'}), '客诉明细': dict(RENAME_ALL_DF_COLUMNS, **{'门店id': '站点ID', '履约单号＃号后': '履约单号'}), '配送超时明细': dict(RENAME_ALL_DF_COLUMNS, **{'履约单号＃号后': '履约单号'}), '配送原因取消明细': dict(RENAME_ALL_DF_COLUMNS, **{'配送原因未完成订单号': '订单ID', '履约单号＃号后': '履约单号'}), '违规点送达明细': dict(RENAME_ALL_DF_COLUMNS, **{'履约单号＃号后': '履约单号'}), '骑手出勤明细': dict(RENAME_ALL_DF_COLUMNS, **{'arrange_def_name': '排班'})}
def RENAME_CALLBACK(name: str) -> Any:
    ...

def delete_and_create(db: Any, df: polars.DataFrame, date_column: Any, default_site_name_column: Any, default_site_id_column: Any) -> None:
    ...

def 匹配灯塔客诉到线下客诉明细中(data_date: date | list[date], is_month: bool) -> None:
    ...

class 核心数据解析(UnzipExcelFilesManager):
    def __init__(self: Self, zip_path: str | BytesIO) -> None: ...
    @classmethod
    def 计算超时类型(cls, df: polars.DataFrame, 送达时间_key: str, 考核时间_key: str, new_col: str) -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import re
import datetime
import io
import typing
import polars
import zghmvp
import zghmvp.apps
import zghmvp.apps.report
import zghmvp.apps.report.models
import zghmvp.apps.report.tools
import zghmvp.apps.report.tools.format
import zghmvp.config
import zghmvp.tools
import zghmvp.tools.format
import zghmvp.tools.pl
import zghmvp.apps.report.tools.dengta