# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from datetime import date, datetime
from types import ModuleType
from typing import Any, Callable, TYPE_CHECKING, overload
from zghmvp.apps.base import models
from zghmvp.apps.report.tools.播报.p202601.base import Base考核方式
from zghmvp.tools import typed_cache
import importlib
import statistics

class 考核工具:
    @classmethod
    def _get_module(cls, data_date: date | datetime) -> ModuleType: ...
    @classmethod
    def 获取_考核方式(cls, data_date: date | datetime) -> Callable[..., 'Base考核方式']: ...
    @classmethod
    def 获取_工作周(cls, d: int | datetime | date) -> str: ...
    @classmethod
    def 日播报(cls, data_date: date | datetime) -> Any: ...
    @classmethod
    def 月播报(cls, data_date: date | datetime) -> Any: ...

class 得分计算:
    @staticmethod
    def calculate_score(thresholds: list[float], scores: list[float], rate: float) -> float: ...
    @staticmethod
    def 计算_正向指标_得分(率值: str | float | int, 考核方案: dict, 分数: int | float | None) -> float: ...
    @staticmethod
    def 计算_负向指标_得分(率值: str | float | int, 考核方案: dict, 分数: int | float | None) -> float: ...
    @staticmethod
    def 计算_骑手行为异常率_得分(率值: float, 考核方案: dict) -> float: ...
    @classmethod
    def 计算_区间得分(cls, 区间: list[float], 得分: list[float], 率值: float) -> float: ...
    @staticmethod
    def 计算_百分比_变化率(被除数列: float, 除数列: float) -> float: ...
    @staticmethod
    def 计算_百分比_占比(被除数列: float, 除数列: float, 是否取反: bool) -> float: ...

def get_site_parent_tree() -> tuple[base_models.城市, base_models.区域, base_models.站点]:
    ...

def get_site_parent_tree() -> tuple[base_models.城市, base_models.区域, base_models.站点]:
    ...

def get_site_parent_tree() -> tuple[base_models.城市, base_models.区域, None]:
    ...

def get_site_parent_tree() -> tuple[base_models.城市, base_models.区域, None]:
    ...

def get_site_parent_tree() -> tuple[base_models.城市, None, None]:
    ...

def get_site_parent_tree() -> tuple[base_models.城市, None, None]:
    ...

def get_site_parent_tree(city_name: str | None, city_id: int | None, areal_name: str | None, areal_id: int | None, site_name: str | None, site_id: int | None) -> tuple[base_models.城市 | None, base_models.区域 | None, base_models.站点 | None]:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import importlib
import statistics
import datetime
import types
import typing
import zghmvp
import zghmvp.apps
import zghmvp.apps.base
import zghmvp.apps.base.models
import zghmvp.tools
import zghmvp.tools.typed_cache