# Generated by Django 6.0.1 on 2026-01-19 06:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='应用ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='应用名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='应用说明')),
                ('enable_time', models.DateTimeField(blank=True, null=True, verbose_name='启用时间')),
                ('disable_time', models.DateTimeField(blank=True, null=True, verbose_name='停用时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '应用',
                'verbose_name_plural': '应用列表',
                'ordering': ['-enable_time'],
            },
        ),
        migrations.CreateModel(
            name='VersionFile',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='文件Hash')),
                ('file', models.FileField(upload_to='nuitkal-pack', verbose_name='文件')),
                ('name', models.CharField(max_length=255, verbose_name='文件名')),
                ('size', models.BigIntegerField(verbose_name='文件大小(字节)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '版本文件',
                'verbose_name_plural': '版本文件列表',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(db_index=True, max_length=50, verbose_name='版本号')),
                ('entry_point', models.CharField(max_length=255, verbose_name='程序入口路径')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('changelog', models.TextField(blank=True, null=True, verbose_name='更新日志')),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='是否激活')),
                ('file_manifest', models.JSONField(default=dict, verbose_name='文件清单')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appversion_set', to='nuitkal_pack_server.app', verbose_name='所属应用')),
            ],
            options={
                'verbose_name': '客户端版本',
                'verbose_name_plural': '客户端版本列表',
                'ordering': ['-upload_time'],
                'unique_together': {('app', 'version')},
            },
        ),
    ]
