# Generated by Django 6.0.1 on 2026-01-17 09:19

import django.db.models.deletion
import nuitkal_pack_server.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.CharField(help_text='系统自动生成的唯一标识符', max_length=32, primary_key=True, serialize=False, verbose_name='唯一标识')),
                ('name', models.CharField(help_text='应用的名称,不可为空', max_length=100, unique=True, verbose_name='应用名称')),
                ('description', models.TextField(blank=True, help_text='应用的详细说明', null=True, verbose_name='应用说明')),
                ('enable_time', models.DateTimeField(blank=True, help_text='应用开始可用的时间', null=True, verbose_name='启用时间')),
                ('disable_time', models.DateTimeField(blank=True, help_text='应用停止可用的时间,为空表示永不停止', null=True, verbose_name='停用时间')),
            ],
            options={
                'verbose_name': '应用',
                'verbose_name_plural': '应用',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClientVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='语义化版本号,如 1.0.1', max_length=50, verbose_name='版本号')),
                ('file', models.FileField(help_text='ZIP 格式的更新包文件', max_length=255, upload_to='client_updates/%Y/%m/', validators=[nuitkal_pack_server.models.validate_zip_file], verbose_name='文件路径')),
                ('entry_point', models.CharField(blank=True, default='main.py', help_text='更新后的程序启动文件,仅支持 .py, .sh, .bat, .cmd, .exe 格式', max_length=255, validators=[nuitkal_pack_server.models.validate_entry_point], verbose_name='程序入口路径')),
                ('file_size', models.IntegerField(blank=True, help_text='更新包文件大小', null=True, verbose_name='文件大小(字节)')),
                ('file_hash', models.CharField(blank=True, help_text='SHA256 哈希值,用于校验文件完整性', max_length=64, verbose_name='文件哈希')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('changelog', models.TextField(help_text='版本更新说明', verbose_name='更新日志')),
                ('is_active', models.BooleanField(default=False, help_text='仅一个版本可为 True', verbose_name='是否为当前推荐版本')),
                ('app', models.ForeignKey(help_text='版本所属的应用', on_delete=django.db.models.deletion.CASCADE, related_name='client_versions', to='nuitkal_pack_server.app', verbose_name='所属应用')),
            ],
            options={
                'verbose_name': '客户端版本',
                'verbose_name_plural': '客户端版本',
                'ordering': ['-upload_time'],
                'constraints': [models.UniqueConstraint(fields=('app', 'version'), name='unique_app_version')],
            },
        ),
    ]
