# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from dingtalkchatbot.chatbot import DingtalkChatbot
from tenacity import retry, stop_after_attempt, wait_random
from typing import Any
from typing_extensions import Self
from zghmvp.apps.report.tools.browser import AutoRenewalRedisLock
from zghmvp.apps.report.tools.log import PrintLineStatus
from zghmvp.tools import redis_lock
from zghmvp.tools.system import copy_files_to_clipboard, is_debugging
import imghdr
import io
import os
import pathlib
import pythoncom
import requests
import subprocess
import threading
import time
import uiautomation

class ZGHMVPBoot:
    def __init__(self: Self) -> None: ...
    def _get_access_token(self: Self) -> None: ...
    def _upload_file(self: Self, file_path: Any) -> Any: ...
    def _upload_single(self: Self, file_path: Any) -> Any: ...
    def send_single_chat(self: Self, title: str, content: str, file_paths: list[str] | None) -> None: ...
    def _send_file(self: Self, media_id: Any) -> None: ...
    def send(self: Self, file_path: Any) -> None: ...

def update_image_to_server(path: str | io.BytesIO) -> str:
    ...

def extract_text_by_at_symbol(text: Any) -> Any:
    ...

def safe_exists(ctrl_func: Any, timeout: Any) -> Any:
    ...

class DingtalkAuto:
    def __init__(self: Self, exe_path: str) -> None: ...
    def _搜索粘贴群名称(self: Self, group_name: Any, type_name: str) -> None: ...
    def send_msg(self: Self, group_name: str, files: list | None, images: list | None, text: str, type_name: str) -> None: ...
    def 发送到质量管控(self: Self, city_name: Any, files: list | None, images: list | None, text: str) -> None: ...
    def lock(self: Self) -> None: ...
    def unlock(self: Self) -> None: ...
    def __enter__(self: Self) -> Any: ...
    def __exit__(self: Self, exc_type: Any, exc_val: Any, exc_tb: Any) -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import imghdr
import io
import os
import pathlib
import subprocess
import threading
import time
import pythoncom
import requests
import uiautomation
import dingtalkchatbot
import dingtalkchatbot.chatbot
import tenacity
import tenacity.retry
import tenacity.stop_after_attempt
import tenacity.wait_random
import zghmvp
import zghmvp.apps
import zghmvp.apps.report
import zghmvp.apps.report.tools
import zghmvp.apps.report.tools.browser
import zghmvp.apps.report.tools.log
import zghmvp.tools
import zghmvp.tools.redis_lock
import zghmvp.tools.system
import ntpath