# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from django_redis import get_redis_connection
from patchright.async_api import Page
from patchright.async_api._context_manager import PlaywrightContextManager
from pathlib import Path
from redis import Redis
from typing import Any, Literal
from typing_extensions import Self
from zghmvp.apps.report.tools.log import PrintBlock
from zghmvp.tools import redis_lock
from zghmvp.tools.pl import PlTools
from zghmvp.tools.system import is_debugging
import asyncio
import contextlib
import io
import os
import polars
import random

redis_client: Redis = get_redis_connection('default')
class RedisLock:
    def __init__(self: Self, name: str, expire: Any | None, id: Any | None, auto_renewal: bool, strict: bool, signal_expire: int) -> None: ...

class AutoRenewalRedisLock:
    def __init__(self: Self, name: str, id: Any | None) -> None: ...

class AsyncTabManager(PrintBlock):
    def __init__(self: Self, browser_manager: 'AsyncBrowserManager', title: str, print_time: bool) -> None: ...

class AsyncBrowserManager(PlaywrightContextManager):
    def __init__(self: Self, endpoint_url: str, close_all_page: bool, close_open_page: bool, init_script: str | None) -> None: ...

def async_browser_manage_func(endpoint_url: str, close_all_page: bool, close_open_page: bool, init_script: str | None) -> Any:
    ...

def async_browser_manage_func_run(endpoint_url: str, close_all_page: bool, close_open_page: bool, init_script: str | None) -> Any:
    ...

df: polars.DataFrame = PlTools.read_excel(download)
df = download
df: polars.DataFrame = PlTools.read_excel(download)

__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import asyncio
import contextlib
import io
import os
import random
import pathlib
import typing
import polars
import django_redis
import django_redis.get_redis_connection
import patchright
import patchright.async_api
import patchright.async_api.Page
import patchright.async_api._context_manager
import redis
import redis.Redis
import zghmvp
import zghmvp.apps
import zghmvp.apps.report
import zghmvp.apps.report.tools
import zghmvp.apps.report.tools.log
import zghmvp.tools
import zghmvp.tools.redis_lock
import zghmvp.tools.pl
import zghmvp.tools.system