# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from collections import defaultdict
from dataclasses import dataclass, field
from datetime import date, datetime, timedelta
from django.db import transaction
from itertools import chain
from patchright._impl._async_base import AsyncEventInfo
from patchright.async_api._generated import Frame, Locator, Page, Response
from pathlib import Path
from tenacity import retry, stop_after_attempt, wait_random
from typing import Any, Literal, cast, overload
from typing_extensions import Self
from zghmvp.apps.base import models
from zghmvp.apps.report import models
from zghmvp.apps.report.tools.browser import AsyncBrowserManager, AsyncTabManager, excel_to_parquet, random_sleep_async
from zghmvp.apps.report.tools.format import format_and_create, format_site_info
from zghmvp.tools.cache_memoize import CacheProxy
from zghmvp.tools.format import auto_datetime_convert, fromtimestamp, parse_int
from dataclasses import dataclass
import asyncio
import polars
import re

申诉中心_违规申诉_默认查询分类 = ['上报异常违规取消', '违规补时', '虚假点送达', '未送达指定地点', '虚假治理']
申诉中心_违规申诉_查询详情分类 = ['上报异常违规取消', '违规补时', '虚假治理']
申诉中心_违规申诉_超时与取消 = ['超时订单', '取消订单', '预约单提前送达', '严重超时']
申诉中心_违规申诉_客诉 = ['服务态度差', '丢餐', '预约单提前送达', '破损撒漏', '化冻', '鲜活商品死亡', '未送达指定地点', '内部[异味/结块/发粘]', '整单送错', '部分商品/赠品/免费菜少送', '未按照备注配送', '配送超时']
@dataclass
class NotificationItem:
class PageManager(AsyncTabManager):
class DownloadManager:
    def __init__(self: Self, root: '灯塔', title_pattern: re.Pattern[str]) -> None: ...

class 灯塔:
    def __init__(self: Self, browser_manager: AsyncBrowserManager) -> None: ...
    def env(self: Self, title: str, print_time: bool) -> Any: ...
    def env_wait_download(self: Self, reg_title: re.Pattern[str]) -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import asyncio
import re
import collections
import collections.defaultdict
import dataclasses
import datetime
import itertools
import pathlib
import typing
import polars
import django
import django.db
import django.db.transaction
import patchright
import patchright._impl
import patchright._impl._async_base
import patchright.async_api
import patchright.async_api._generated
import tenacity
import tenacity.retry
import tenacity.stop_after_attempt
import tenacity.wait_random
import zghmvp
import zghmvp.apps
import zghmvp.apps.base
import zghmvp.apps.base.models
import zghmvp.apps.report
import zghmvp.apps.report.models
import zghmvp.apps.report.tools
import zghmvp.apps.report.tools.browser
import zghmvp.apps.report.tools.format
import zghmvp.tools
import zghmvp.tools.cache_memoize
import zghmvp.tools.format