# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from datetime import date, datetime
from typing_extensions import Self
from zghmvp.apps.report.tools.path import get_date_data_dir
from zghmvp.config import BASE_DIR
from zghmvp.tools.excel import ExcelTemplateScreenshot
from zghmvp.tools.system import is_debugging
import os

class ExcelTemplateScreenshot(ExcelTemplateScreenshotBase):
    def __init__(self: Self, template_name: str) -> None: ...
    def save_to(self: Self, save_path: str | None) -> str: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import datetime
import zghmvp
import zghmvp.apps
import zghmvp.apps.report
import zghmvp.apps.report.tools
import zghmvp.apps.report.tools.path
import zghmvp.config
import zghmvp.tools
import zghmvp.tools.excel
import zghmvp.tools.system