# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from django.db import models, transaction
from django.db.models import F
from ordered_set import OrderedSet
from typing import Any, Type
from zghmvp.apps.base import models
from zghmvp.apps.report.tools.log import PrintLineStatus
from zghmvp.tools.models import get_date_fields, get_datetime_fields, get_fields, get_float_fields, get_int_fields
from zghmvp.tools.pl import PlTools, TRenameConfigType
import polars

def format_site_info(df: polars.DataFrame) -> Any:
    ...

def format_field_data(base_model: Any, df: polars.DataFrame) -> Any:
    ...

def format_and_create(base_model: Type[models.Model], df: polars.DataFrame) -> polars.DataFrame:
    ...

def format_and_create_or_update(base_model: Type[models.Model], unique_fields: list[str], df: polars.DataFrame) -> Any:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import typing
import polars
import django
import django.db
import django.db.models
import django.db.transaction
import django.db.models.F
import ordered_set
import ordered_set.OrderedSet
import zghmvp
import zghmvp.apps
import zghmvp.apps.base
import zghmvp.apps.base.models
import zghmvp.apps.report
import zghmvp.apps.report.tools
import zghmvp.apps.report.tools.log
import zghmvp.tools
import zghmvp.tools.models
import zghmvp.tools.pl