# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from datetime import date, datetime, timedelta
from django.db.models import Q
from patchright._impl._async_base import AsyncEventInfo
from patchright.async_api._generated import Download, Page, Response
from typing import Any, cast
from typing_extensions import Self
from zghmvp.apps.base import models
from zghmvp.apps.report import models
from zghmvp.apps.report.tools.browser import AsyncBrowserManager, AsyncTabManager, excel_to_parquet, random_sleep_async
from zghmvp.apps.report.tools.log import PrintLineStatus
from zghmvp.apps.report.tools.path import get_date_data_dir
from zghmvp.apps.report.tools.数据工具.考核工具 import 考核工具
from zghmvp.config import SUPPLIER_ID, SUPPLIER_NAME, 大象审核群ID
from zghmvp.tools.cache_memoize import CacheProxy
from zghmvp.tools.format import auto_datetime_convert
from zghmvp.tools.pl import PlTools
from zghmvp.tools_old.fmt import format_and_create, format_site_info, get_site_error_name
import asyncio
import calendar
import contextlib
import inspect
import itertools
import json
import numpy
import os
import pandas
import polars
import re

rename_实时监控看板_实时监控_维度数据监控 = {'site_name': '站点名称', 'origin_transport_ontime_rate': '配送准时率', 'dispatch_overstock_order_cnt': '待分拣单量', 'dispatch_begin_not_trans_order_cnt': '分拣未推配送单量', 'leave_transport_overstock_order_cnt': '配送积压单量', 'transport_overstock_order_cnt': '待揽收', 'transporting_way_order_cnt': '配送在途单量', 'after_transport_cancel_order_cnt': '推配后取消单量', 'serious_transport_timeout_order_cnt': '配送超时10分钟单量', 'transport_timeout_order_cnt': '配送超时单量', 'transport_end_order_cnt': '配送完成单量'}
class 订单计算:
    def __init__(self: Self) -> None: ...
    @staticmethod
    def __推配时段明细合计(value: pandas.Series) -> Any: ...
    @classmethod
    def __init_骑手完成单量(cls, df_骑手单量明细: pandas.DataFrame, data_date: date, agg_args: dict) -> Any: ...
    @classmethod
    def __init_站点完成单量(cls, model: Any, df_骑手单量明细: pandas.DataFrame, data_date: date, agg_args: dict) -> Any: ...
    @classmethod
    def 灯塔_骑手完成单量(cls, data_date: date) -> Any: ...
    @classmethod
    def 灯塔_站点完成单量(cls, data_date: date) -> Any: ...
    @classmethod
    def 灯塔_城市区域完成单量(cls, data_date: date) -> None: ...
    @classmethod
    def 获取工作日非工作日天数(cls, site_id: int) -> dict: ...
    @classmethod
    def 看板_骑手完成单量(cls, data_date: date) -> Any: ...
    @classmethod
    def 看板_站点完成单量(cls, data_date: date) -> Any: ...
    @classmethod
    def 看板_城市区域完成单量(cls, data_date: date) -> None: ...

class 看板:
    def __init__(self: Self, browser_manager: AsyncBrowserManager) -> None: ...
    def env(self: Self, title: str, print_time: bool) -> Any: ...
    def env_wait_download(self: Self) -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import asyncio
import calendar
import contextlib
import inspect
import itertools
import json
import os
import re
import datetime
import typing
import numpy
import pandas
import polars
import django
import django.db
import django.db.models
import django.db.models.Q
import patchright
import patchright._impl
import patchright._impl._async_base
import patchright.async_api
import patchright.async_api._generated
import zghmvp
import zghmvp.apps
import zghmvp.apps.base
import zghmvp.apps.base.models
import zghmvp.apps.report
import zghmvp.apps.report.models
import zghmvp.apps.report.tools
import zghmvp.apps.report.tools.browser
import zghmvp.apps.report.tools.log
import zghmvp.apps.report.tools.path
import zghmvp.apps.report.tools.数据工具
import zghmvp.apps.report.tools.数据工具.考核工具
import zghmvp.config
import zghmvp.tools
import zghmvp.tools.cache_memoize
import zghmvp.tools.format
import zghmvp.tools.pl
import zghmvp.tools_old
import zghmvp.tools_old.fmt