# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from django.db import models
from django.db.models.expressions import Combinable
from typing import ClassVar, Generic, Self, TypeVar
from typing_extensions import Self
from zghmvp.tools.models import BaseModel, get_fields_to_schema
from dataclasses import dataclass
import hashlib
import polars

class PolarsQuerySet:
    def to_polars(self: Self, fields: tuple[str, ...] | list[str]) -> polars.DataFrame: ...
    def is_success(self: Self, status: bool | None) -> bool: ...

T = TypeVar('T')

class PolarsManager(Generic[T]):
    def get_queryset(self: Self) -> PolarsQuerySet: ...
    def to_polars(self: Self, fields: tuple[str, ...] | list[str]) -> polars.DataFrame: ...
    def is_success(self: Self, status: bool | None) -> bool: ...

@dataclass
class BaseModel(_BaseModel):
    class Meta:

__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import hashlib
import typing
import polars
import django
import django.db
import django.db.models
import django.db.models.expressions
import zghmvp
import zghmvp.tools
import zghmvp.tools.models
import zghmvp.apps
import zghmvp.apps.report
import zghmvp.apps.report.models
import zghmvp.apps.report.models.base