# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from datetime import date, datetime, timedelta
from zghmvp.config import FILE_SAVE_DIR
import os

def get_date_data_dir(data_date: datetime | date, make_dir: bool, sub_dir: str | None, file_name: str | None) -> str:
    ...

def get_today_data_dir(make_dir: bool, sub_dir: str | None, file_name: str | None) -> str:
    ...

def get_yesterday_data_dir(make_dir: bool, sub_dir: str | None, file_name: str | None) -> str:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import datetime
import zghmvp
import zghmvp.config
import ntpath