# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from dataclasses import dataclass
from datetime import date, datetime
from django.core.cache import caches
from django.core.cache.backends.base import DEFAULT_TIMEOUT
from django.db import models
from django.utils.encoding import force_bytes
from functools import wraps
from pathlib import Path, WindowsPath
from typing import Any, Literal, Union
from typing_extensions import Self
from urllib.parse import quote
from zghmvp.tools.file_type import filetype
from dataclasses import dataclass
import hashlib
import inspect
import io
import itertools
import json
import os
import time

DEFAULT_CACHE_ALIAS = 'tuke-cache'
def cache_memoize(timeout: Any, prefix: Any, extra: Any, args_rewrite: Any, hit_callable: Any, miss_callable: Any, key_generator_callable: Any, store_result: Any, cache_exceptions: Any, cache_alias: Any) -> Any:
    ...

@dataclass
class TypeDefault:
@dataclass
class TypeFile:
@dataclass
class CacheProxy:
    def __init__(self: Self, key: str, data_date: list[date | datetime] | date | datetime | None) -> None: ...
    @staticmethod
    def _format_date(obj: date | datetime) -> str: ...
    def date_key(self: Self) -> str: ...
    def set(self: Self, value: Any) -> Any: ...
    def get(self: Self) -> TypeDefault | None: ...
    def get_value(self: Self) -> Any | None: ...
    def set_file(self: Self, file: str | bytes | WindowsPath | Path) -> Any: ...
    def get_file(self: Self) -> io.BytesIO: ...
    def is_exists(self: Self) -> bool: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import hashlib
import inspect
import io
import itertools
import json
import os
import time
import dataclasses
import datetime
import functools
import pathlib
import typing
import urllib
import urllib.parse
import django
import django.core
import django.core.cache
import django.core.cache.caches
import django.core.cache.backends
import django.core.cache.backends.base
import django.db
import django.db.models
import django.utils
import django.utils.encoding
import zghmvp
import zghmvp.tools
import zghmvp.tools.file_type
import ntpath