# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from PIL import ImageGrab
from datetime import date, datetime
from pathlib import Path
from typing import Any, IO, overload
from typing_extensions import Self
from zghmvp.tools.system import is_debugging
from dataclasses import dataclass
import io
import os
import polars
import time
import xlwings

TSheetType = int | str | xlwings.Sheet
TPathType = str | Path
@dataclass
class ExcelTemplate:
    def __init__(self: Self, template_path: TPathType) -> None: ...
    def __enter__(self: Self) -> Any: ...
    def __exit__(self: Self, exc_type: Any, exc_value: Any, traceback: Any) -> Any: ...
    def get_sheet(self: Self, sheet: TSheetType) -> xlwings.Sheet: ...
    def copy_sheet(self: Self, sheet: TSheetType) -> xlwings.Sheet: ...
    def append_value(self: Self, df: polars.DataFrame, sheet: TSheetType) -> tuple[int, xlwings.Sheet]: ...
    def save_to(self: Self, save_path: TPathType | IO[bytes]) -> Path | IO[bytes]: ...
    def delete_order_sheets(self: Self, names: list[str]) -> None: ...

class ExcelTemplateScreenshot(ExcelTemplate):
    def screenshot(self: Self, sheet: xlwings.Sheet, save_path: TPathType) -> Path: ...
    def screenshot(self: Self, sheet: xlwings.Sheet, save_path: IO[bytes] | None) -> IO[bytes]: ...
    def screenshot(self: Self, sheet: xlwings.Sheet, save_path: TPathType | IO[bytes] | None) -> Path | IO[bytes]: ...
    def append_value_and_screenshot(self: Self, df: polars.DataFrame, save_path: TPathType | IO[bytes] | None) -> Path | IO[bytes]: ...
    def fill_city_config(self: Self, city_name: str, df_config: polars.DataFrame) -> None: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import io
import os
import time
import datetime
import pathlib
import typing
import polars
import xlwings
import PIL
import PIL.ImageGrab
import zghmvp
import zghmvp.tools
import zghmvp.tools.system