# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from typing_extensions import Self
import filetype

class ParquetMatcher:
    def __init__(self: Self) -> None: ...
    def match(self: Self, buf: bytes) -> bool: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import filetype