# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from collections.abc import Callable
from datetime import date, datetime
from dateutil import parser
from functools import wraps
from typing import Any, ParamSpec, TypeVar, Union, get_args, get_origin, overload
import asyncio
import inspect
import types

R = TypeVar('R')

def auto_datetime_convert(func: Callable[P, R]) -> Callable[P, R]:
    ...

def parse_int(s: Any, default: int) -> int:
    ...

def parse_float(s: Any, default: float, is_percentage: bool) -> float:
    ...

def fromtimestamp(t: Any, format_str: None) -> datetime | None:
    ...

def fromtimestamp(t: Any, format_str: str) -> str | None:
    ...

def fromtimestamp(t: Any, format_str: str | None) -> Any:
    ...

def parse_time_range(time_range: str) -> list[int]:
    ...

def parse_date(date_str: str) -> date:
    ...

def dict_keys_rename(data: dict, rename_map: dict) -> dict:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import asyncio
import inspect
import types
import collections
import collections.abc
import datetime
import functools
import typing
import dateutil
import dateutil.parser