# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from collections.abc import Callable
from datetime import datetime, timedelta
import os
import time

def wait_input_file_path(suffix: tuple[str, ...], msg: str) -> str:
    ...

def wait_input_dir_path(msg: str) -> str:
    ...

def wait_input_excel_file_path(msg: str) -> str:
    ...

def wait_input_date(msg: str, format_str: str, default: Callable[..., datetime] | datetime | None) -> datetime:
    ...

def wait_input_date_range(msg: str, format_str: str, default: Callable[..., tuple[datetime, datetime]] | tuple[datetime, datetime] | datetime | None) -> tuple[datetime, datetime]:
    ...

def wait_input_zip_file_path(msg: str) -> str:
    ...

def wait_time(days: int, seconds: int, microseconds: int, milliseconds: int, minutes: int, hours: int, weeks: int, name: str) -> None:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import time
import collections
import collections.abc
import datetime