# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from django.db import models
from django.db.models.expressions import Combinable
from types import MappingProxyType
from typing import Any
from typing_extensions import Self
from zghmvp.tools import typed_cache
import polars

class CustomAttrNameForeignKey:
    def __init__(self: Self) -> None: ...
    def get_attname(self: Self) -> Any: ...

def get_fields_for_type(model: type[models.Model], class_or_tuple: tuple, exclude: tuple[str, ...] | list[str]) -> dict[str, models.Field]:
    ...

def get_fields(model: type[models.Model], exclude: tuple[str, ...] | list[str]) -> dict[str, models.Field]:
    ...

def get_time_fields(model: type[models.Model], exclude: tuple[str, ...] | list[str]) -> dict[str, models.Field]:
    ...

def get_datetime_fields(model: type[models.Model], exclude: tuple[str, ...] | list[str]) -> dict[str, models.Field]:
    ...

def get_date_fields(model: type[models.Model], exclude: tuple[str, ...] | list[str]) -> dict[str, models.Field]:
    ...

def get_int_fields(model: type[models.Model], exclude: tuple[str, ...] | list[str]) -> dict[str, models.Field]:
    ...

def get_float_fields(model: type[models.Model], exclude: tuple[str, ...] | list[str]) -> dict[str, models.Field]:
    ...

def get_number_fields(model: type[models.Model], exclude: tuple[str, ...] | list[str]) -> dict[str, models.Field]:
    ...

db_types = {models.IntegerField: lambda field: polars.Int32, models.AutoField: lambda field: polars.Int32, models.BigAutoField: lambda field: polars.Int64, models.BigIntegerField: lambda field: polars.Int64, models.FloatField: lambda field: polars.Float64, models.DateTimeField: lambda field: polars.Datetime, models.DateField: lambda field: polars.Date, models.BooleanField: lambda field: polars.Boolean, models.CharField: lambda field: polars.Utf8, models.TextField: lambda field: polars.Utf8, models.EmailField: lambda field: polars.Utf8, models.URLField: lambda field: polars.Utf8, models.GenericIPAddressField: lambda field: polars.Utf8, models.FileField: lambda field: polars.Utf8, models.ImageField: lambda field: polars.Utf8, models.DecimalField: lambda field: polars.Decimal(field.max_digits, field.decimal_places)}
def get_fields_to_schema(model: type[models.Model], columns: tuple[str, ...] | list[str], exclude: tuple[str, ...] | list[str]) -> dict[str, polars.DataType]:
    ...

def get_fields_default_value(model: type[models.Model], columns: tuple[str, ...] | list[str], exclude: tuple[str, ...] | list[str]) -> dict[str, polars.DataType]:
    ...

def polars_fill_default_expr(model: type[models.Model], columns: tuple[str, ...] | list[str]) -> list[polars.Expr]:
    ...

class BaseModel:
    class Meta:
    @classmethod
    def get_attname_to_verbose_name_dict(cls, ) -> Any: ...
    @classmethod
    def get_verbose_name_to_attname_dict(cls, ) -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import types
import polars
import django
import django.db
import django.db.models
import django.db.models.expressions
import zghmvp
import zghmvp.tools
import zghmvp.tools.typed_cache