# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
from tempfile import TemporaryDirectory
from typing import Any, MutableMapping, cast, overload
from typing_extensions import Self
from dataclasses import dataclass
import diskcache
import hashlib
import io
import logging
import pathspec
import platform
import re
import subprocess
import sys
import zipfile

LOG_FORMAT = '%(asctime)s - %(levelname)s - %(message)s'
LOG_DATE_FORMAT = '%Y-%m-%d %H:%M:%S'
def calculate_hash(file_path: Path | bytes | str, buffer_size: int) -> str:
    ...

@dataclass
class BuildFile:
    def __post_init__(self: Self) -> Any: ...

def compile_with_nuitka(full_path: Path, rel_path: Path) -> tuple[BuildFile, BuildFile]:
    ...

class PythonPackager:
    def __init__(self: Self, source_dir: Path) -> None: ...
    def _setup_logger(self: Self, level: int) -> logging.Logger: ...
    def __del__(self: Self) -> Any: ...
    def rglob_exclude(self: Self, root: Path, patterns: list[str] | tuple[str, ...], exclude_files: list[str] | tuple[str, ...]) -> Any: ...
    def compile(self: Self, rglob_pattern: list[str] | tuple[str, ...]) -> Any: ...
    def to_zip(self: Self, user_name: str) -> io.BytesIO: ...
    def to_zip(self: Self, user_name: None) -> MutableMapping[str, io.BytesIO]: ...
    def to_zip(self: Self, user_name: str | None, exclude_hashes: list[str] | tuple[str, ...]) -> MutableMapping[str, io.BytesIO] | io.BytesIO: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import hashlib
import io
import logging
import platform
import re
import subprocess
import sys
import zipfile
import collections
import collections.defaultdict
import dataclasses
import pathlib
import tempfile
import typing
import diskcache
import pathspec