# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from typing import Any, Callable, Dict, List, Type
from typing_extensions import Self
import ast
import inspect
import os
import textwrap

class ASTMethodInjector:
    def __init__(self: Self) -> None: ...
    def add(self: Self, target_class: Type) -> Callable: ...
    def add_import(self: Self, target_class_or_file: Any, items: List[Any]) -> Any: ...
    def __enter__(self: Self) -> Any: ...
    def __exit__(self: Self, exc_type: Any, exc_val: Any, exc_tb: Any) -> Any: ...
    def _apply_all_imports(self: Self) -> Any: ...
    def _apply_all_patches(self: Self) -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import ast
import inspect
import os
import textwrap
import typing