# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from collections import UserDict, defaultdict
from collections.abc import Callable, Generator
from dataclasses import dataclass, field
from functools import cached_property
from io import BytesIO
from ordered_set import OrderedSet
from pathlib import Path
from polars._typing import FileSource, SchemaDict
from tempfile import TemporaryDirectory
from typing import IO, Literal, Optional, Set, Tuple, Union, get_args
from typing_extensions import TypeAlias
from zghmvp.tools.file_type import filetype
from zghmvp.tools.zipfile import ZipFile
from dataclasses import dataclass
import contextlib
import os
import polars
import re
import types

TDataFrameFileType: TypeAlias = Literal['.xlsx', '.xls', '.csv', '.parquet']
TRenameConfigType = str | re.Pattern[str] | Callable[[str], str] | dict[str, str] | dict[re.Pattern[str], str]
TPath = Path | str
TPaths = TPath | list[TPath] | tuple[TPath, ...]
TListStr = tuple[str, ...] | list[str]
class PlTools:
    @classmethod
    def replace_null_strings(cls, df: polars.DataFrame, null_strings: TListStr) -> polars.DataFrame: ...
    @classmethod
    def auto_cast(cls, df: polars.DataFrame, exclude_cols: TListStr) -> polars.DataFrame: ...
    @staticmethod
    def rename_with_rules(name: str, config: TRenameConfigType) -> str | None: ...
    @classmethod
    def rename_with_columns(cls, df: polars.DataFrame, config: TRenameConfigType) -> polars.DataFrame: ...
    @classmethod
    def sort_columns_front(cls, df: polars.DataFrame, priority_columns: TListStr) -> polars.DataFrame: ...
    @classmethod
    def read_excel(cls, path: FileSource, schema_overrides: SchemaDict | None) -> polars.DataFrame: ...
    @classmethod
    def read_file(cls, path: TPath | IO[bytes], schema_overrides: SchemaDict | None) -> polars.DataFrame: ...
    @classmethod
    def save_to(cls, df: polars.DataFrame, save_path: TPath | IO[bytes]) -> None: ...
    @staticmethod
    def drop_columns(df: polars.DataFrame, columns: TListStr) -> polars.DataFrame: ...
    @staticmethod
    def date_2_str(df: polars.DataFrame, date_format: str, datetime_format: str) -> polars.DataFrame: ...

@dataclass
class DictDataFrameItem:
    def df(self: Self) -> polars.DataFrame: ...

class DictDataFrame(UserDict):
    def __init__(self: Self) -> None: ...
    def remove(self: Self, key: str) -> polars.DataFrame: ...
    def copy(self: Self) -> 'DictDataFrame': ...
    def items(self: Self) -> Generator[tuple[str, polars.DataFrame], None, None]: ...
    def __getitem__(self: Self, key: str) -> polars.DataFrame: ...
    def __setitem__(self: Self, key: str, value: TPaths | polars.DataFrame | DictDataFrameItem) -> None: ...

def get_all_file_path(directory: TPath) -> Generator[Path, None, None]:
    ...

def get_all_file_to_dataframe(directory: TPath, filter_file_name: re.Pattern[str] | None) -> Generator[polars.DataFrame, None, None]:
    ...

def get_all_file_to_dict_dataframe(directory: TPath, rename: TRenameConfigType | None, schema_overrides_with_file: dict[str, SchemaDict] | None, null_strings: TListStr) -> DictDataFrame | dict[str, polars.DataFrame]:
    ...

class UnzipExcelFilesManager:
    def __init__(self: Self, path: TPath | IO[bytes]) -> None: ...
    def format(self: Self) -> None: ...
    def save_to(self: Self, save_to: TPath | BytesIO) -> None: ...
    def __enter__(self: Self) -> 'UnzipExcelFilesManager': ...
    def __exit__(self: Self, exc_type: Optional[type[BaseException]], exc_val: Optional[BaseException], exc_tb: Optional[types.TracebackType]) -> Literal[False]: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import contextlib
import os
import re
import types
import collections
import collections.UserDict
import collections.defaultdict
import collections.abc
import dataclasses
import functools
import io
import pathlib
import tempfile
import typing
import polars
import ordered_set
import ordered_set.OrderedSet
import polars._typing
import zghmvp
import zghmvp.tools
import zghmvp.tools.file_type
import zghmvp.tools.zipfile