# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from base64 import b64encode
from logging import getLogger
from os import urandom
from redis import StrictRedis
from typing import Any, Union
from typing_extensions import Self
from dataclasses import dataclass
import threading
import time
import weakref

__version__ = '4.0.0'
UNLOCK_SCRIPT = b'\n    if redis.call("get", KEYS[1]) ~= ARGV[1] then\n        return 1\n    else\n        redis.call("del", KEYS[2])\n        redis.call("lpush", KEYS[2], 1)\n        redis.call("pexpire", KEYS[2], ARGV[2])\n        redis.call("del", KEYS[1])\n        return 0\n    end\n'
EXTEND_SCRIPT = b'\n    if redis.call("get", KEYS[1]) ~= ARGV[1] then\n        return 1\n    elseif redis.call("ttl", KEYS[1]) < 0 then\n        return 2\n    else\n        redis.call("expire", KEYS[1], ARGV[2])\n        return 0\n    end\n'
RESET_SCRIPT = b"\n    redis.call('del', KEYS[2])\n    redis.call('lpush', KEYS[2], 1)\n    redis.call('pexpire', KEYS[2], ARGV[2])\n    return redis.call('del', KEYS[1])\n"
RESET_ALL_SCRIPT = b"\n    local locks = redis.call('keys', 'lock:*')\n    local signal\n    for _, lock in pairs(locks) do\n        signal = 'lock-signal:' .. string.sub(lock, 6)\n        redis.call('del', signal)\n        redis.call('lpush', signal, 1)\n        redis.call('expire', signal, 1)\n        redis.call('del', lock)\n    end\n    return #locks\n"
class AlreadyAcquired(RuntimeError):
class NotAcquired(RuntimeError):
class AlreadyStarted(RuntimeError):
class TimeoutNotUsable(RuntimeError):
class InvalidTimeout(RuntimeError):
class TimeoutTooLarge(RuntimeError):
class NotExpirable(RuntimeError):
@dataclass
class Lock(object):
    def __init__(self: Self, redis_client: Any, name: Any, expire: Any, id: Any, auto_renewal: Any, strict: Any, signal_expire: Any) -> None: ...
    @classmethod
    def register_scripts(cls, redis_client: Any) -> Any: ...
    def _held(self: Self) -> Any: ...
    def reset(self: Self) -> Any: ...
    def id(self: Self) -> Any: ...
    def get_owner_id(self: Self) -> Any: ...
    def acquire(self: Self, blocking: Any, timeout: Any) -> Any: ...
    def extend(self: Self, expire: Any) -> Any: ...
    @staticmethod
    def _lock_renewer(name: Any, lockref: Any, interval: Any, stop: Any) -> Any: ...
    def _start_lock_renewer(self: Self) -> Any: ...
    def _stop_lock_renewer(self: Self) -> Any: ...
    def __enter__(self: Self) -> Any: ...
    def __exit__(self: Self, exc_type: Any, exc_value: Any, traceback: Any) -> Any: ...
    def release(self: Self) -> Any: ...
    def locked(self: Self) -> Any: ...

reset_all_script = None
def reset_all(redis_client: Any) -> Any:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import threading
import time
import weakref
import base64
import logging
import logging.getLogger
import os
import typing
import redis
import redis.StrictRedis