# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from PIL import Image
from pathlib import Path
from types import ModuleType
from typing import Generator
import ctypes
import importlib
import io
import os
import pathspec
import sys
import time
import win32clipboard
import yaml

def autodiscover_apps() -> list[str]:
    ...

def load_config(file_name: str) -> dict[str, dict]:
    ...

def is_debugging() -> bool:
    ...

def copy_files_to_clipboard(filepaths_list: list[str | Path] | str | Path) -> None:
    ...

def copy_image_to_clipboard(path: str | Path) -> None:
    ...

def turn_off_screen(off: bool) -> None:
    ...

def get_dir_modules(root_dir: str | Path) -> Generator[ModuleType, None, None]:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import ctypes
import importlib
import io
import os
import sys
import time
import pathlib
import types
import typing
import pathspec
import win32clipboard
import yaml
import PIL
import PIL.Image